package com.touhid.project.uber.uberApp.entities;

import com.touhid.project.uber.uberApp.enums.PaymentMethod;
import com.touhid.project.uber.uberApp.enums.RideStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.locationtech.jts.geom.Point;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(indexes = {
        @Index(name = "idx_rider",columnList = "rider_rider_id"),
        @Index(name = "idx_driver",columnList = "driver_driver_id")
})
public class Ride {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long rideId;

    @Column(columnDefinition = "Geometry(Point,4326)")
    private Point pickupLocation;  // Geographic point representing the pickup location of the ride request, stored using WGS 84 coordinate system.

    @Column(columnDefinition = "Geometry(Point,4326)")
    private Point dropOffLocation;  // Geographic point representing the drop-off location of the ride request, stored using WGS 84 coordinate system.

    @CreationTimestamp
    private LocalDateTime rideCreatedTime;  // Timestamp for when the ride request was created, automatically generated by Hibernate.

    @ManyToOne(fetch = FetchType.EAGER)
    private Rider rider;

    @ManyToOne(fetch = FetchType.LAZY)
    private Driver driver;

    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    @Enumerated(EnumType.STRING)
    private RideStatus rideStatus;

    private String otp;

    private Double fare;

    private LocalDateTime startedAt;
    private LocalDateTime endedAt;

    @OneToOne(mappedBy = "ride", cascade = CascadeType.ALL)
    private Payment payment;


}
